bids_app_args:
    --skip-bids-validation: Null

singularity_args:
    - --no-home
    - --writable-tmpfs
# Output foldername(s) to be zipped:
zip_foldernames:
    sink: "test"
# How much cluster resources it needs:
cluster_resources:
    interpreting_shell: "/bin/bash"
    customized_text: |
        #SBATCH --partition=mit_preemptable
        #SBATCH --cpus-per-task=8
        #SBATCH --mem=12G
        #SBATCH --time=00:30:00
        #SBATCH --job-name=fsl_bidsapp
# Necessary commands to be run first:
script_preamble: |
    source activate /home/djarecka/.conda/envs/simple_babs_test
    module load apptainer/1.1.9
# Where to run the jobs:
job_compute_space: "/orcd/scratch/bcs/001/djarecka/manual_test_babs/working_dir"
required_files:
    $INPUT_DATASET_#1:
        - "anat/*_T1w.nii*"
# Alert messages that might be found in log files of failed jobs:
alert_log_messages:
    stdout:
        - "ERROR:"
        - "Cannot allocate memory"
        - "mris_curvature_stats: Could not open file"
        - "Numerical result out of range"
